config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cuisines, only: [:index, :show] do
    resources :restaurants, only: [:create]
  end

  resources :restaurants, only: [:show, :index] do
    resources :upvotes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :messages, only: [:create, :index]
  end

  resources :users, only: [:show] do 
    resources :follows, only: [:create, :destroy]
  end

  resources :dishes, only: [:create] 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # validates :bio, presence: true

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :follower_follows, foreign_key: :followed_id, class_name: "Follow", dependent: :destroy

  belongs_to :cuisine
  has_many :reviews

  has_many :followers, through: :follower_follows, source: "follower"
  has_many :followings, through: :following_follows, source: "followed"
  has_one_attached :photo

  def has_upvoted?(resto)
    upvotes = Upvote.where(user: self, restaurant: resto)
    upvotes.length > 0
  end

  def can_upvote?(restaurant)
    self.cuisine.name == restaurant.cuisine.name
  end

  def has_favorited?(resto)
    favorites = Favorite.where(user: self, restaurant: resto)
    favorites.length > 0
  end

  def following?(user)
    follows = Follow.exists?(follower: self, followed: user)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]
  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user: @user)
      @follow_users = Follow.where(follower_id: params[:id])
      @followed_users = Follow.where(followed_id: params[:id])
  end
end
# ne pas oublié de mettre :photo dans user_params

app/views/users/show.html.erb
<div class= "background_profile">
  <div class="cover-banner user-banner">
  </div>
  	<% if @user.photo.attached? %>
  	  <%= cl_image_tag @user.photo.key, class: "profile-avatar" %>
  	<% else %>
  	  <%= image_tag "https://media.wired.com/photos/5a13e24f63f8d15055c806fe/master/pass/hulk-still-bg.jpg", class: "profile-avatar" %>
  	<% end %>
</div>

<div class="favorite-vote">
  <% if user_signed_in? %>
    <% if current_user.id != @user.id %>
      <% if current_user.following?(@user) %>
        <%= link_to user_follow_path(@user), method: :delete, remote: true do %>
          <%= image_tag 'user_followed.svg', {class: 'user-followed'} %>
        <% end %>
      <% else %>
        <%= link_to user_follows_path(@user), method: :post, remote: true do %>
          <%= image_tag 'follow_user.svg', {class: 'user-followed'} %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<h3 class= "user_name" style="margin-top: 30px;"> <strong><%= @user.first_name %><strong></h3>
<h4 class= "user_cuisine"> <%= Cuisine.where(id: @user&.cuisine_id)&.first&.name %> Cuisine Expert</h4>
<hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">
<div class= "user_bio">
  <p style="text-align: center;"><%= @user.bio %></p>
</div>

<hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">

<h2 style="font-weight: bold; font-size: 23px; text-align: center; margin-top: 25px;">Favorited Restaurants</h2>
  <div class="horizontal-scroll grid-three">
    <% @favorites.each do |favorite| %>
      <div class="my-3">
        <%= render "shared/medium_restaurant_card", {restaurant: favorite.restaurant} %>
      </div>
    <% end %>
  </div>
<div class= "profile_small"> </div>
	<!-- Recently upvoted restaurant cards -->
<hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">


<h2 style="font-weight: bold; font-size: 23px; text-align: center; margin-top: 25px;">Followers (<%= @followed_users.count %>)</h2>
<div class="container">
  <% if @followed_users.empty? %>
    <div class="no-follower-box">
      <p>no followers yet</p>
    </div>
  <% else %>
    <div class="horizontal-scroll grid-three">
      <% @followed_users.each do |follow| %>
        <div class="follower-avatar">
          <%= link_to user_path(follow.follower) do %>
            <% if follow.follower.photo.attached? %>
              <%= cl_image_tag follow.follower.photo.key, class: "avatar-follow" %>
            <% else %>
              <%= image_tag "https://media.wired.com/photos/5a13e24f63f8d15055c806fe/master/pass/hulk-still-bg.jpg", class: "profile-avatar" %>
            <% end %>
          <% end %>
          <h3><%= follow.follower.first_name %></h3>
          <p> <%= follow.follower.cuisine.name %> cuisine </p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<h2 style="font-weight: bold; font-size: 23px; text-align: center; margin-top: 25px;">Following (<%= @follow_users.count %>)</h2>
<div class="container">
  <% if @follow_users.empty? %>
    <div class="no-follower-box">
      <p>not following anyone yet</p>
    </div>
  <% else %>
    <div class="horizontal-scroll grid-three">
      <% @follow_users.each do |follow| %>
        <div class="follower-avatar">
          <%= link_to user_path(follow.followed) do %>
            <% if follow.followed.photo.attached? %>
              <%= cl_image_tag follow.followed.photo.key, class: "avatar-follow" %>
            <% else %>
              <%= image_tag "https://media.wired.com/photos/5a13e24f63f8d15055c806fe/master/pass/hulk-still-bg.jpg", class: "profile-avatar" %>
            <% end %>
          <% end %>
          <h3><%= follow.followed.first_name %></h3>
          <p> <%= follow.followed.cuisine.name %> cuisine </p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>