config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cuisines, only: [:index, :show] do
    resources :restaurants, only: [:create]
  end

  resources :restaurants, only: [:show, :index] do
    resources :upvotes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :messages, only: [:create, :index]
  end

  resources :users, only: [:show] do 
    resources :follows, only: [:create, :destroy]
  end

  resources :dishes, only: [:create] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :restaurant
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurants
  has_many :users
  validates :name, presence: true

  has_one_attached :photo

  def cuisine_upvoted
    restaurants.select do |restaurant|
      cuisine_experts = users.count
      restaurant_upvotes = Upvote.where(restaurant: restaurant).count
      global_threshold = 0.4

      upvote_percentage = restaurant_upvotes / cuisine_experts.to_f
      upvote_percentage >= global_threshold
    end
  end

  def pending_cuisine
    restaurants.to_a.select do |restaurant|
      cuisine_experts = users.count
      restaurant_upvotes = Upvote.where(restaurant: restaurant).count
      global_threshold = 0.4

      upvote_percentage = restaurant_upvotes / cuisine_experts.to_f
      upvote_percentage < global_threshold
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :restaurants, through: :tags
  has_many :users, through: :tags
  validates :name, presence: true
  has_one_attached :photo
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  has_one_attached :photo
end

app/models/follow.rb
class Follow < ApplicationRecord
   belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
   belongs_to :followed, foreign_key: 'followed_id', class_name: 'User'
   has_one_attached :photo
   
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user

  validates :content, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :cuisine
  has_many :users, through: :upvotes
  has_many :users, through: :reviews
  has_many :users, through: :favorites
  has_many :users, through: :tags
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :dishes, through: :tags
  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_restaurant_or_dish,
    against: :name,
     associated_against: {
      cuisine: [:name],
      dishes:[:name]
     },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  def self.upvoted
    self.all.select do |restaurant|
      cuisine_experts = restaurant.cuisine.users.count
      restaurant_upvotes = Upvote.where(restaurant: restaurant).count
      global_threshold = 0.5

      upvote_percentage = restaurant_upvotes / cuisine_experts.to_f
      upvote_percentage >= global_threshold
    end
  end

  def self.latest_upvoted
    global = self.upvoted
    global = global.sort { |r1, r2|  r2.upvotes.last.created_at <=> r1.upvotes.last.created_at }
    global = global[0..11] if global.length > 10
    global
  end

  def neat_address
    self.address.split(',')[0..1].join(',')
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_one_attached :photo
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :dish
  belongs_to :restaurant
  belongs_to :user
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # validates :bio, presence: true

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :follower_follows, foreign_key: :followed_id, class_name: "Follow", dependent: :destroy

  belongs_to :cuisine
  has_many :reviews

  has_many :followers, through: :follower_follows, source: "follower"
  has_many :followings, through: :following_follows, source: "followed"
  has_one_attached :photo

  def has_upvoted?(resto)
    upvotes = Upvote.where(user: self, restaurant: resto)
    upvotes.length > 0
  end

  def can_upvote?(restaurant)
    self.cuisine.name == restaurant.cuisine.name
  end

  def has_favorited?(resto)
    favorites = Favorite.where(user: self, restaurant: resto)
    favorites.length > 0
  end

  def following?(user)
    follows = Follow.exists?(follower: self, followed: user)
  end 
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def create
    dish = Dish.create(dish_params)
    @restaurant = Restaurant.find(params[:dish][:restaurant_id])
    tag = Tag.create(dish: dish, restaurant: @restaurant, user: current_user)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def dish_params
    params.require(:dish).permit(:name)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @follow = Follow.new(follower: current_user, followed: @user)
    if @follow.save
      redirect_to user_path(@user)
    else
      flash[:warning] = "Could not follow. Please try again!"
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @follow = Follow.where(follower: current_user, followed: @user).first
    @follow.destroy

    redirect_to user_path(@user)
  end

end
# ne pas oublié de mettre :photo dans follow_params

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @cuisines = Cuisine.all
    @restaurants = Restaurant.latest_upvoted
    @cuisine_count = Cuisine.count
    @restaurant_count = Restaurant.count
    @user_count = User.count
  end
end
# ne pas oublié de mettre :photo dans page_params

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @cuisine = @restaurant.cuisine

    if @review.save
      
      redirect_to restaurant_path(@restaurant)
    else

      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :restaurant_id, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @tag = Tag.new(tag_params)
    @tag.restaurant = @restaurant
    if @tag.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]
  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user: @user)
      @follow_users = Follow.where(follower_id: params[:id])
      @followed_users = Follow.where(followed_id: params[:id])
  end
end
# ne pas oublié de mettre :photo dans user_params

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YummyPalette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <%= favicon_link_tag 'favicon.ico'%>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if request.original_url.split("/").last != "sign_in"%>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>

    <%= yield %>

    <% if (request.original_url.split("/").last != "sign_in") && (request.original_url.split("/").last != "sign_up")%>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Background image -->
<div class="cover-banner">
  <div id="title-div">
    <h1 id="title1" class="title">Yummy Palette</h1>
  <!--   <h1 id="title2" class="title">Palette</h1> -->
  </div>
</div>

<div class="container">
  <!-- Palette info icons -->
  <div class="icons_aligned">   
    <div class="info-icons">
      <%= image_tag 'small_orange_palette.svg' %>
      <span class="info-nums"><%= @cuisine_count %></span>
      <div class="intro-info">
        <p>Cuisines to explore</p>
      </div>
    </div>
    <div class="info-icons">
      <%= image_tag 'small_yellow_palette.svg' %>
      <span class="info-nums"><%= @restaurant_count %></span>
      <div class="intro-info">
        <p>Restaurants to discover</p>
      </div>
    </div>
    <div class="info-icons">
      <%= image_tag 'small_green_palette.svg' %>
      <span class="info-nums"><%= @user_count %></span>
      <div class="intro-info">
        <p>Cuisine Experts</p>
      </div>
    </div>
  </div>
</div>
<!-- cuisine index -->
<div class="cards-wrapper">
  <h2 style="font-weight: bold; font-size: 23px; text-align: center;">Cuisines</h2>
  <div class="horizontal-scroll">
    <% @cuisines.each_with_index do |cuisine, i| %>
      <div class="remove-hover-effect card_index_<%= i %>">
        <%= render "shared/small_cuisine_card", {cuisine: cuisine} %>
      </div>
    <% end  %>
  </div> 
</div>

<!-- Recently upvoted restaurant cards -->
<hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">

<h2 style="margin-bottom: 0; margin-top: 20px; font-weight: bold; font-size: 23px; padding-left: 12px; text-align: center; margin-bottom: 15px;">Latest Upvoted Restaurants</h2>

<div class="restaurant_card_container_home">
  <% @restaurants.each do |restaurant| %>
    <div class="my-3">
      <%= render "shared/medium_restaurant_card", {restaurant: restaurant} %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Yummy</p>
  <%= image_tag "logo-black.png", size: "30" %>
  <p>Palette</p>
</div>

app/views/shared/_map_popup.html.erb
<% if restaurant.photo.attached? %>
  <%= cl_image_tag restaurant.photo.key, crop: :fill, class: "card-image" %>
<% else %>
  <img class="card-image" src="https://c8.alamy.com/comp/JB1G0H/food-palette-with-fresh-ingredients-including-herbs-and-spices-JB1G0H.jpg"/>
<% end %>

<div class="popup-inline-text">
  <h3 style="padding-top: 2px;"><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
  <p style="font-weight: bold;"><%= restaurant.cuisine.name %></p>
</div>

<p><%= restaurant.neat_address %></p>

app/views/shared/_medium_avatar.html.erb
<div class="medium-avatar">

	<% if user.cuisine_id %>
  <%= link_to user_path(user) do %>
		<% if user.photo.attached? %>
			<%= cl_image_tag user.photo.key, class: "avatar" %>
		<% else %>
			<%= image_tag "https://media.wired.com/photos/5a13e24f63f8d15055c806fe/master/pass/hulk-still-bg.jpg", class: "avatar" %>
      <% end %>
		<% end %>
	<% end %>
    <p><%= user.first_name %> <%= user.last_name[0] %>.</p>
</div>

app/views/shared/_medium_restaurant_card.html.erb
<div class="restaurant-card-container grow-small">
    <div class="restaurant-card">
        <div class="cuisine-tag"><%= restaurant.cuisine.name %></div>
        <%= link_to restaurant_path(restaurant) do %>
            <% if restaurant.photo.attached? %>
                <%= cl_image_tag restaurant.photo.key, crop: :fill, class: "card-image" %>
            <% else %>
                <img class="card-image" src="https://c8.alamy.com/comp/JB1G0H/food-palette-with-fresh-ingredients-including-herbs-and-spices-JB1G0H.jpg"/>
            <% end %>
        <% end %>
        
        <div class="restaurant-card-footer">
            <div class="restaurant-card-info">
                <h2><%= restaurant.name %></h2>
                <div class="address-container">
                    <%= image_tag 'location_icon.svg', size: "17" %>
                    <p class="location"><%= restaurant.neat_address %></p>
                </div>
            </div>
            <div class="card-extra-info">
                <p><%= image_tag 'black_star.svg', size: "18" %> <%= restaurant.favorites.count %> <%= image_tag 'black_upvote.svg', size: "18" %><%= restaurant.upvotes.count %></p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_message.html.erb
<div class="message-container">
  <% if message.user.photo.attached? %>
    <%= cl_image_tag message.user.photo.key, class:"avatar" %>
  <% end %>
  <div>
    <i class="author">
      <span><%= message.user.first_name %></span>
      <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
    </i>
    <p><%= message.content %></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", size: "80" %>
  <% end %>
  <button class="navbar-toggler" id="nav-button" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">

      <!-- If user is not signed in -->
      <% unless user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cuisines', cuisines_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link text-dark' %>
        </li>
      <% else %>
        <!-- If user is signed in -->
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', user_path(current_user), class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cuisines', cuisines_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My community', cuisine_path(current_user.cuisine), class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
        </li>
      <% end %>

    </ul>
    <%# <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>

    <div class="search-field">
      <div class="search">
        <div class="magnifying-glass">
          <i class="fas fa-search"></i>
        </div>
        <%= form_tag restaurants_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control big-border-radius",
            placeholder: "Search for..."%>
          <%= submit_tag "Search",
            class: "btn btn-primary big-border-radius d-none",
            id: "searchbtn" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_small_cuisine_card.html.erb
<%= link_to cuisine_path(cuisine) do %>
  <div class="small-cuisine-card grow">
    <% if cuisine.photo.attached? %>
      <%= cl_image_tag cuisine.photo.key, crop: :fill %>
    <% else %>
      <img src="https://c8.alamy.com/comp/JB1G0H/food-palette-with-fresh-ingredients-including-herbs-and-spices-JB1G0H.jpg" />
    <% end %>
    <div class="small-cuisine-card-name">
      <span><%= cuisine.name %></span>
    </div>
  </div>
<% end %>