config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cuisines, only: [:index, :show] do
    resources :restaurants, only: [:create]
  end

  resources :restaurants, only: [:show, :index] do
    resources :upvotes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :messages, only: [:create, :index]
  end

  resources :users, only: [:show] do 
    resources :follows, only: [:create, :destroy]
  end

  resources :dishes, only: [:create] 

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :cuisine
  has_many :users, through: :upvotes
  has_many :users, through: :reviews
  has_many :users, through: :favorites
  has_many :users, through: :tags
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :dishes, through: :tags
  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_restaurant_or_dish,
    against: :name,
     associated_against: {
      cuisine: [:name],
      dishes:[:name]
     },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo

  def self.upvoted
    self.all.select do |restaurant|
      cuisine_experts = restaurant.cuisine.users.count
      restaurant_upvotes = Upvote.where(restaurant: restaurant).count
      global_threshold = 0.5

      upvote_percentage = restaurant_upvotes / cuisine_experts.to_f
      upvote_percentage >= global_threshold
    end
  end

  def self.latest_upvoted
    global = self.upvoted
    global = global.sort { |r1, r2|  r2.upvotes.last.created_at <=> r1.upvotes.last.created_at }
    global = global[0..11] if global.length > 10
    global
  end

  def neat_address
    self.address.split(',')[0..1].join(',')
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :index]
  def show
    @restaurant = Restaurant.find(params[:id])
    @dish = Dish.new
    @user = current_user
    @review = Review.new
    @cuisine = @restaurant.cuisine
    @upvote = Upvote.where(user: current_user, restaurant: @restaurant).first
    @favorite = Favorite.where(user: current_user, restaurant: @restaurant).first
  end



  def index
    @restaurants = Restaurant.all
    if params[:query].present?
      @restaurants = Restaurant.search_by_restaurant_or_dish(params[:query])
      @markers = create_markers
    else
      @restaurants = Restaurant.all
      @markers = create_markers
    end
    print @markers
  end

  def create_markers
    # @restaurants_coordinates = Restaurant.where.not(latitude: nil, longitude: nil)
    @restaurants_coordinates = @restaurants.reject { |restaurant| restaurant.latitude.nil? && restaurant.longitude.nil? }
    @restaurants_coordinates.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        mapPopup: render_to_string(partial: "shared/map_popup", locals: { restaurant: restaurant })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @cuisine = Cuisine.find(params[:cuisine_id])
    @restaurant.cuisine = @cuisine
    if @restaurant.save!
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :vegan, :vegetarian, :latitude, :longitude, :photo)
  end
end

app/views/restaurants/index.html.erb
<div class="cuisines-banner">
	<div class="search">  
		<div class="magnifying-glass">
			<i class="fas fa-search"></i>
		</div> 
		<%= form_tag restaurants_path, method: :get do %>
			<%= text_field_tag :query,
			params[:query],
			class: "form-control big-border-radius",
			placeholder: "Search for..."%>
			<%= submit_tag "Search", class: "btn btn-primary big-border-radius d-none", id: "searchbtn" %>
		<% end %> 
	</div> 
</div>

<%# Map %>
<div id="map"
     style="width: 100%; height: 400px; margin-top:25px; margin-bottom: 40px; box-shadow: 0 2px 8px 2px rgba(0, 0, 0, 0.3);"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">

<div class="restaurant_card_container_home">
	<% @restaurants.each do |restaurant| %>
		<div class="my-3">
		<%= render "shared/medium_restaurant_card", {restaurant: restaurant} %>
		</div>
	<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="banner-restaurant">
  <% if @restaurant.photo.attached? %>
    <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://res.cloudinary.com/drjhe1klf/image/upload/c_fill/<%= @restaurant.photo.key %>.jpg); position: absolute; width: 100%; height: 100%; background-size: cover; z-index: -1;">
    </div>
  <% else %>
    <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://c8.alamy.com/comp/JB1G0H/food-palette-with-fresh-ingredients-including-herbs-and-spices-JB1G0H.jpg); position: absolute; width: 100%; height: 100%; background-size: cover; z-index: -1">
    </div>
  <% end %>
</div>

<div class="show-container container">
  <div class="restaurant-show-card">
    <h1 class="card-title"><strong><%= @restaurant.name %></strong></h1>
    <%= link_to @cuisine.name, cuisine_path(@cuisine), class: "btn btn-ghost cuisine-tag" %>
    <div class="card-restaurant-infos">
      <p class="orange-icon"><%= image_tag 'location-icon-orange.svg' %> <%= @restaurant.address %></p>
      <p class="orange-icon"><%= image_tag 'phone-icon-orange.svg' %> <%= @restaurant.phone %></p>
      <p class="orange-icon"><%= image_tag 'website-icon-orange.svg' %>www.yummypaletteapp.com</p>
    </div>
    <br>
    <hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 0 auto;">
    <div class="favorite-vote">
      <% if !user_signed_in? %>
        <%= link_to new_user_registration_path do %>
          <%= image_tag 'yellow-star-filled.svg', {id: 'yellow_star_filled'} %>
        <% end %>
      <% elsif current_user.has_favorited?(@restaurant) %>
        <%= link_to restaurant_favorite_path(@restaurant, @favorite), method: :delete, remote: true do %>
          <%= image_tag 'yellow-star-filled.svg', {id: 'yellow_star_filled'} %>
        <% end %>
      <% else %>
        <%= link_to restaurant_favorites_path(@restaurant), method: :post, remote: true do %>
          <%= image_tag 'empty_grey_star.svg' %>
        <% end %>
      <% end %>
      <div class="upvote-box">
        <% if !user_signed_in? %>
          <%= image_tag 'black_upvote.svg' %>
        <% elsif current_user.can_upvote?(@restaurant) %>
          <% if current_user.has_upvoted?(@restaurant) %>
            <%= link_to restaurant_upvote_path(@restaurant, @upvote), method: :delete, remote: true do %>
              <%= image_tag 'red-upvote-filled.svg', {id: 'red-upvote'} %>
            <% end %>
          <% else %>
            <%= link_to restaurant_upvotes_path(@restaurant), method: :post, remote: true do %>
              <%= image_tag 'empty_grey_upvote.svg' %>
            <% end %>
          <% end %>
        <% else %>
          <%= image_tag 'black_upvote.svg' %>
        <% end %>
        <span><%= @restaurant.upvotes.count %></span>
      </div>
    </div>
  </div>

  <% if user_signed_in? && current_user.cuisine == @restaurant.cuisine %>
    <%= link_to "Enter Chatroom", restaurant_messages_path(@restaurant), class:"btn btn-outline-primary ask-btn enter-chatroom-button", 'data-retaurant-id' => @restaurant.id %>
  <% end %>
  <!-- Best dishes card -->
  <h1 style="font-size: 23px; font-weight: bold;">Best dishes</h1>
  <div class="best-dishes">
    <div class="flex-card">
      <% @restaurant.tags.each do |tag| %>
        <div class="tag">
          <p><%= tag.dish.name%></p>
        </div>
      <% end %>

      <!-- Add Dish trigger modal -->
      <% if user_signed_in? %>
        <% if current_user.cuisine&.name == @cuisine.name %>
          <button type="button" class="tag" style="width: 50px;" data-toggle="modal" data-target="#tagModal">
            +
          </button>
        <% end %>
      <% end %>
      <!-- Modal -->
      <div class="modal fade" id="tagModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content add-dish-modal">
            <h5 class="modal_restaurant_name"><%= link_to @restaurant.name, restaurant_path(@restaurant) %></h5>
            <div class="modal-body">
              <p class="add-dish">Add your favorite dish</p>
              <%= simple_form_for(@dish) do |f| %>
                <%= f.input :name, label: false %>
                <%= f.input :restaurant_id, :as => :hidden, :class => "add-dish-area", :input_html => { :value => @restaurant.id } %>
                <div class="d-flex justify-content-center">
                  <%= f.submit 'Submit', class: "submit-button-blue" %>
                  <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button> %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- end of add Dish -->
    </div>
  </div>
  <!-- end of Best Dish -->

  <!-- Review card -->
  <h1 style="font-size: 23px; font-weight: bold;">Why we recommend this Restaurant</h1>
  <% @restaurant.reviews.each do |review| %>
    <% if review.user.cuisine&.name == @cuisine.name %>
      <div class="review_card">
        <div class="avatar">
          <% if review.user.photo.attached? %>
            <%= link_to user_path(review.user) do %>
              <%= cl_image_tag review.user.photo.key, class: "avatar" %>
            <% end %>
          <% end %>
        </div>
        <div class="review-dish">
          <div class="expert-name">
            <span><%= review.user.first_name %></span>
            <span class="cuisine-name"><%= review.user.cuisine.name %> Expert</span>
          </div>
          <div class="expert-review">
            <p><%= review.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <!-- Add Review trigger modal -->
  <% if user_signed_in? %>
    <% if current_user.cuisine&.name == @cuisine.name %>
      <button type="button" class="btn-review" data-toggle="modal" data-target="#reviewModal">Add a Review</button>
    <% end %>
  <% end %>
  <!-- Modal -->
  <div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content review-modal">
        <h5 class="modal_restaurant_name"><%= link_to @restaurant.name, restaurant_path(@restaurant) %></h5>
        <div class="modal-body">
          <% if user_signed_in? %>
            <% if current_user.cuisine&.name == @cuisine.name %>
              <p>Leave a review</p>
            <% else %>
              <p>Leave a comment</p>
            <% end %>
            <%= simple_form_for([@restaurant, @review]) do |f| %>
              <%= f.input :content, label: false %>
              <%= f.input :restaurant_id, :as => :hidden, :class => "add-review-area", :input_html => { :value => @restaurant.id } %>
              <%= f.input :user_id, :as => :hidden, :class => "add-review-area", :input_html => { :value => @user.id } %>
              <div class="d-flex justify-content-center">
                <%= f.submit 'Submit', class: "submit-button-blue" %>
                <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button> %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- end of add Review -->

  <hr style="border: 1px solid rgba(187, 187, 187, 0.41); width:95%; text-align:center; margin: 20px; auto;">

  <!-- Comments of guests -->
  <h1 style="font-size: 23px; font-weight: bold;">Guests comments</h1>
  <% @restaurant.reviews.each do |review| %>
    <% unless review.user.cuisine&.name == @cuisine.name %>
      <div class="review_card">
        <div class="avatar">
          <% if review.user.photo.attached? %>
            <%= link_to user_path(review.user) do %>
              <%= cl_image_tag review.user.photo.key, class: "avatar" %>
            <% end %>
          <% end %>
          <!--<h3><%#= current_user.first_name</h3> %>-->
        </div>
        <div class="review-dish">
          <div class="expert-name">
            <span><%= review.user.first_name %></span>
            <span class="cuisine-name"><%= review.user.cuisine&.name %> Expert</span>
          </div>
          <div class="expert-review">
            <p><%= review.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <% unless current_user.cuisine.name == @cuisine.name %>
      <button type="button" class="btn-review" data-toggle="modal" data-target="#reviewModal">Add a Comment</button>
    <% end %>
  <% end %>
    <!-- end comments of guests -->
</div>